research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst

# New tasks for incident management
collect_error_logs_task:
  description: >
    Collect all error logs from middleware.io for the past {hours_to_search} hours. 
    Filter the logs to focus on ERROR and FATAL severity levels.
    Look for any patterns or recurring issues that might indicate a system problem.
  expected_output: >
    A comprehensive set of error logs from the system that can be used for further analysis.
    Include timestamps, severity levels, and the full error messages.
  agent: log_collector

analyze_logs_task:
  description: >
    Analyze the collected error logs to identify patterns, root causes, and potential solutions.
    Look for common failure points, service dependencies, and environmental factors.
    Determine which services are most affected and what might be causing the issues.
  expected_output: >
    A detailed analysis report that identifies the root cause of the errors,
    affected services, impact assessment, and recommended actions to resolve the issues.
  agent: log_analyzer

create_incident_task:
  description: >
    Create a properly documented incident in Jira Service Management based on the log analysis.
    Include all relevant details such as affected services, root cause analysis, and recommended actions.
    Assign appropriate priority based on the severity and impact of the issue.
  expected_output: >
    A confirmation that the incident has been created in JSM with all necessary details.
    The incident should include a clear summary, detailed description, appropriate priority,
    and any components or services that are affected.
  agent: incident_manager
