# JSM State-Driven Workflow Configuration

# Workflow States mapped to JSM ticket statuses
workflow_states:
  # Initial states
  INCIDENT_DETECTED: "To Do"
  ANALYSIS_IN_PROGRESS: "In Progress" 
  ANALYSIS_COMPLETE: "Analysis Complete"
  
  # Fix generation states
  FIX_GENERATION_IN_PROGRESS: "Generating Fix"
  FIX_GENERATED: "Fix Generated"
  
  # PR management states  
  PR_CREATION_IN_PROGRESS: "Creating PR"
  PR_CREATED: "PR Created"
  PR_UNDER_REVIEW: "Under Review"
  PR_APPROVED: "PR Approved"
  PR_MERGED: "PR Merged"
  
  # Deployment states
  DEPLOYMENT_IN_PROGRESS: "Deploying"
  DEPLOYMENT_COMPLETE: "Deployed"
  
  # Verification states
  VERIFICATION_IN_PROGRESS: "Verifying Fix"
  VERIFICATION_COMPLETE: "Verification Complete"
  
  # Final states
  INCIDENT_RESOLVED: "Done"
  INCIDENT_FAILED: "Failed"
  INCIDENT_REQUIRES_HUMAN: "Needs Human Intervention"

# State transitions and responsible agents
state_transitions:
  INCIDENT_DETECTED:
    agent: "jira_monitor"
    next_states: ["ANALYSIS_IN_PROGRESS", "INCIDENT_REQUIRES_HUMAN"]
    max_retry_count: 3
    
  ANALYSIS_IN_PROGRESS:
    agent: "root_cause_analyzer"
    next_states: ["ANALYSIS_COMPLETE", "INCIDENT_REQUIRES_HUMAN"]
    max_retry_count: 2
    timeout_minutes: 30
    
  ANALYSIS_COMPLETE:
    agent: "code_fix_generator"
    next_states: ["FIX_GENERATION_IN_PROGRESS"]
    auto_transition: true
    
  FIX_GENERATION_IN_PROGRESS:
    agent: "code_fix_generator"
    next_states: ["FIX_GENERATED", "INCIDENT_REQUIRES_HUMAN"]
    max_retry_count: 2
    timeout_minutes: 45
    
  FIX_GENERATED:
    agent: "pr_manager"
    next_states: ["PR_CREATION_IN_PROGRESS"]
    auto_transition: true
    
  PR_CREATION_IN_PROGRESS:
    agent: "pr_manager"
    next_states: ["PR_CREATED", "INCIDENT_REQUIRES_HUMAN"]
    max_retry_count: 2
    timeout_minutes: 15
    
  PR_CREATED:
    # Human intervention point - waiting for review
    agent: "pr_manager"
    next_states: ["PR_UNDER_REVIEW", "PR_APPROVED", "INCIDENT_REQUIRES_HUMAN"]
    requires_human: true
    check_interval_minutes: 30
    max_wait_hours: 24
    
  PR_UNDER_REVIEW:
    # Human intervention point - waiting for approval  
    agent: "pr_manager"
    next_states: ["PR_APPROVED", "INCIDENT_REQUIRES_HUMAN"]
    requires_human: true
    check_interval_minutes: 60
    max_wait_hours: 48
    
  PR_APPROVED:
    # Can be automated or require human merge
    agent: "pr_manager"
    next_states: ["PR_MERGED", "INCIDENT_REQUIRES_HUMAN"]
    auto_merge_if_approved: true
    max_retry_count: 3
    
  PR_MERGED:
    agent: "deployment_monitor"
    next_states: ["DEPLOYMENT_IN_PROGRESS"]
    auto_transition: true
    wait_for_ci_cd: true
    
  DEPLOYMENT_IN_PROGRESS:
    agent: "deployment_monitor"
    next_states: ["DEPLOYMENT_COMPLETE", "INCIDENT_REQUIRES_HUMAN"]
    monitor_interval_minutes: 5
    max_wait_minutes: 60
    
  DEPLOYMENT_COMPLETE:
    agent: "deployment_monitor"
    next_states: ["VERIFICATION_IN_PROGRESS"]
    auto_transition: true
    
  VERIFICATION_IN_PROGRESS:
    agent: "deployment_monitor"
    next_states: ["VERIFICATION_COMPLETE", "INCIDENT_REQUIRES_HUMAN"]
    verification_wait_minutes: 15
    max_retry_count: 3
    
  VERIFICATION_COMPLETE:
    agent: "deployment_monitor"  
    next_states: ["INCIDENT_RESOLVED"]
    auto_transition: true

# Polling configuration for state checks
polling_config:
  default_interval_minutes: 15
  max_polling_hours: 72
  exponential_backoff: true
  max_backoff_minutes: 120

# Escalation rules
escalation_rules:
  # If stuck in human review too long
  PR_UNDER_REVIEW:
    escalate_after_hours: 24
    escalate_to_status: "INCIDENT_REQUIRES_HUMAN"
    escalate_assignee: "sre-team-lead"
    
  # If deployment takes too long
  DEPLOYMENT_IN_PROGRESS:
    escalate_after_minutes: 120
    escalate_to_status: "INCIDENT_REQUIRES_HUMAN"
    escalate_assignee: "devops-team"
    
  # If verification fails repeatedly
  VERIFICATION_IN_PROGRESS:
    escalate_after_retries: 5
    escalate_to_status: "INCIDENT_REQUIRES_HUMAN"
    escalate_assignee: "sre-team"

# Retry and timeout configuration
retry_config:
  default_max_retries: 3
  default_timeout_minutes: 30
  exponential_backoff_factor: 2
  max_backoff_minutes: 60
