apiVersion: v1
kind: Secret
metadata:
  name: autonomous-sre-bot-secrets
  namespace: monitoring
type: Opaque
stringData:
  # AI Model Configuration
  OPENAI_API_KEY: "your-deepseek-api-key"
  OPENAI_API_BASE: "https://api.deepseek.com"
  OPENAI_MODEL_NAME: "deepseek/deepseek-chat"
  
  # Middleware.io Configuration
  MIDDLEWARE_API_KEY: "your-middleware-api-key"
  
    # Atlassian Integration (JSM and MCP)
  ATLASSIAN_CLOUD_ID: "your-atlassian-cloud-id"
  ATLASSIAN_TOKEN: "your-atlassian-access-token"
  ATLASSIAN_SERVICE_DESK_ID: "your-service-desk-id"
  ATLASSIAN_REQUEST_TYPE_ID: "your-request-type-id"
  ATLASSIAN_USER_ID: "your-atlassian-user-id"
  ATLASSIAN_URL: "https://yoursite.atlassian.net"
  
  # Langfuse Monitoring Configuration (Optional)
  LANGFUSE_PUBLIC_KEY: "your-langfuse-public-key"
  LANGFUSE_SECRET_KEY: "your-langfuse-secret-key"
  LANGFUSE_HOST: "https://cloud.langfuse.com"
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://cloud.langfuse.com/api/public/otel"