apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: autonomous-sre-bot
  namespace: monitoring
  labels:
    app: autonomous-sre-bot
spec:
  selector:
    matchLabels:
      app: autonomous-sre-bot
  template:
    metadata:
      labels:
        app: autonomous-sre-bot
    spec:
      containers:
      - name: autonomous-sre-bot
        image: autonomous-sre-bot:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: TZ
          value: "UTC"
        # Mount secrets and config maps if needed
        volumeMounts:
        - name: config-volume
          mountPath: /app/.env
          subPath: .env
      volumes:
      - name: config-volume
        secret:
          secretName: autonomous-sre-bot-env
      # This init container will sleep and execute the main container on schedule
      initContainers:
      - name: schedule-runner
        image: alpine:latest
        command: 
        - /bin/sh
        - -c
        - |
          while true; do
            echo "Starting autonomous SRE bot job at $(date)"
            # Touch a file to trigger the main container
            touch /tmp/start-job
            # Wait for 1 hour before next run
            sleep 3600
          done